apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443" 
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:572730696074:certificate/5621ca04-f60b-43b5-ae7c-52e35cfddeab" # Replace with your ACM certificate ARN
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
  - port: 443
    targetPort: 80
    protocol: TCP

